name: AkzuwoFormulaOne
version: '${project.version}'
main: ch.akzuwo.akzuwoformulaone.AkzuwoFormulaOnePlugin
api-version: '1.21'
author: Akzuwo
description: Formula 1 style boat racing system with custom physics and track management.
softdepend:
  - Multiverse-Core
  - RankPointsAPI

commands:
  f1:
    description: AkzuwoFormulaOne user commands.
    usage: /f1
    permission: akzuwoformulaone.user
  f1builder:
    description: AkzuwoFormulaOne track builder commands.
    usage: /f1builder
    permission: akzuwoformulaone.builder
  f1mod:
    description: AkzuwoFormulaOne moderation commands.
    usage: /f1mod
    permission: akzuwoformulaone.mod
  f1admin:
    description: AkzuwoFormulaOne administration commands.
    usage: /f1admin
    permission: akzuwoformulaone.admin

permissions:
  akzuwoformulaone.user:
    description: Allows use of /f1.
    default: true
  akzuwoformulaone.user.join:
    default: true
  akzuwoformulaone.user.leave:
    default: true
  akzuwoformulaone.user.start:
    default: true
  akzuwoformulaone.user.leaderboard:
    default: true
  akzuwoformulaone.mod:
    default: op
  akzuwoformulaone.mod.cancel:
    default: op
  akzuwoformulaone.mod.kick:
    default: op
  akzuwoformulaone.mod.tp:
    default: op
  akzuwoformulaone.mod.info:
    default: op
  akzuwoformulaone.admin:
    default: op
  akzuwoformulaone.admin.reload:
    default: op
  akzuwoformulaone.admin.debug:
    default: op
  akzuwoformulaone.admin.resourcepack:
    default: op
  akzuwoformulaone.admin.physics:
    default: op
  formulaboat.admin.analytics:
    default: op
  formulaboat.admin.analytics.testcrash:
    default: op
  formulaboat.admin.points:
    default: op
  formulaboat.admin.points.test:
    default: op
  akzuwoformulaone.builder:
    default: op
  akzuwoformulaone.builder.create:
    default: op
  akzuwoformulaone.builder.edit:
    default: op
  akzuwoformulaone.builder.checkpoint:
    default: op
  akzuwoformulaone.builder.save:
    default: op
  akzuwoformulaone.builder.enable:
    default: op
